services:
  api:
    build:
      dockerfile: .docker/api/Dockerfile
    container_name: taco-rp-api
    depends_on:
      db:
        condition: service_healthy
    ports:
    - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/docs"]
      interval: 30s
      timeout: 10s
      retries: 5
    stdin_open: true
    tty: true
    volumes:
      - ./api/app:/api/app

  fxserver:
    build:
      dockerfile: .docker/fivem/Dockerfile
    container_name: taco-rp-fivem
    depends_on:
      api:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      - "40120:40120"
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - server:/FXServer/server
      - ./resources:/FXServer/server-data/resources
      - ./server.cfg:/FXServer/server-data/server.cfg

  db:
    image: postgres:15.3
    container_name: taco-rp-postgres
    restart: always
    environment:
      POSTGRES_DB: tacoRPDb
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  server:
  db_volume:
