"""add player table

Revision ID: cc042f4f52f7
Revises:
Create Date: 2023-06-21 04:36:18.281304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cc042f4f52f7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_name", sa.String(), nullable=True),
        sa.Column("steam", sa.String(), nullable=True),
        sa.Column("fivem", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("is_logged_in", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_fivem"), "players", ["fivem"], unique=True)
    op.create_index(op.f("ix_players_id"), "players", ["id"], unique=False)
    op.create_index(
        op.f("ix_players_player_name"), "players", ["player_name"], unique=True
    )
    op.create_index(op.f("ix_players_steam"), "players", ["steam"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_players_steam"), table_name="players")
    op.drop_index(op.f("ix_players_player_name"), table_name="players")
    op.drop_index(op.f("ix_players_id"), table_name="players")
    op.drop_index(op.f("ix_players_fivem"), table_name="players")
    op.drop_table("players")
    # ### end Alembic commands ###
